### ISSUE TITLE
Source of New Guinea land cover data

### ISSUE THREAD

**Issue by gaiteiro** [Nowosad/lopata#63]
Hi, I wonder if could you tell me where the land cover data comes from?

I was trying to get hold of a dataset that includes all of Papua New Guinea and the 2 Indonesian provinces (a few bits not included in your example).

**Comment by Nowosad** [comment]
Hi @gaiteiro - the data is a preprocessed (e.g., I cropped the data, simplified the number of classes) version of ESA CCI Land cover product for year 2015. You can find it at https://maps.elie.ucl.ac.be/CCI/viewer/

**Comment by gaiteiro** [comment]
Great! Many thanks for your help. I'll use the motif package to work on this :)
