### ISSUE TITLE
Motif for continuous variable

### ISSUE THREAD

**Issue by ManuelSpinola** [Nowosad/lopata#70]
In the vignette "Types of spatial patterns’ signatures", the 3rd data example is a continuous variable, random_ndvi.  How motif works with that type of variable?

I was thinking that only works with categorical variables.

**Comment by Nowosad** [comment]
Hi @ManuelSpinola -- the NDVI data is only used for the WECOMA signature (see https://jakubnowosad.com/motif/articles/v2_signatures.html#a-weighted-co-occurrence-matrix-wecoma-representation---two-layers). In short, WECOMA takes two raster inputs: one categorical and one continuous. In the example in the vignette, the categorical raster is `landcover` and the continuous raster is `random_ndvi`.
