### ISSUE TITLE
Error in lsp_add_clusters

### ISSUE THREAD

**Issue by ManuelSpinola** [Nowosad/lopata#71]
I am doing clustering with motif.  Everythink works fine until I am trying tu use lsp_add_clusters.html) function.

hi_grid_sf = lsp_add_clusters(hi_cove, hi_clusters, window = g_8km)

Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column

class(hi_cove)
[1] "lsp"        "tbl_df"     "tbl"        "data.frame"

class(hi_clusters)
[1] "integer"

class(g_8km)
[1] "sf"         "data.frame"

**Comment by Nowosad** [comment]
Hi @ManuelSpinola -- can you share your three objects (preferably saved as .rds files) with me? Either here or by email

**Comment by ManuelSpinola** [comment]
Yes, I will send you by email.

**Comment by Nowosad** [comment]
Fixed
